<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <AssemblyName>DBDR.PcCheck</AssemblyName>
    <RootNamespace>Dbdr.PcCheck.App</RootNamespace>
    <Version>0.3.1</Version>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\Brand\DBDRAnticheat.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Dbdr.PcCheck.Core\Dbdr.PcCheck.Core.csproj" />
    <ProjectReference Include="..\Dbdr.PcCheck.Packaging\Dbdr.PcCheck.Packaging.csproj" />
    <ProjectReference Include="..\Dbdr.PcCheck.Windows\Dbdr.PcCheck.Windows.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Assets\Brand\DBDRAnticheat.ico" />
    <Resource Include="Assets\Brand\DBDRAnticheat.png" />
  </ItemGroup>
</Project>
