<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Dbdr.PcCheck.Core\Dbdr.PcCheck.Core.csproj" />
    <ProjectReference Include="..\..\src\Dbdr.PcCheck.Packaging\Dbdr.PcCheck.Packaging.csproj" />
    <ProjectReference Include="..\..\src\Dbdr.PcCheck.Windows\Dbdr.PcCheck.Windows.csproj" />
  </ItemGroup>
</Project>
