<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <AssemblyName>DBDR.PcCheck.Collector</AssemblyName>
    <RootNamespace>Dbdr.PcCheck.Collector.App</RootNamespace>
    <Version>0.1.0</Version>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Collector.Core\Collector.Core.csproj" />
    <ProjectReference Include="..\Collector.Packaging\Collector.Packaging.csproj" />
    <ProjectReference Include="..\Collector.Windows\Collector.Windows.csproj" />
  </ItemGroup>
</Project>
