<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Dbdr.PcCheck.Core\Dbdr.PcCheck.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Diagnostics.EventLog" Version="10.0.0" />
    <PackageReference Include="System.Management" Version="10.0.0" />
  </ItemGroup>
</Project>
